### ISSUE TITLE
Update the README informations

### ISSUE THREAD

**Issue by Akhilian** [OnMyTravel/api#32]

**Comment by trollepierre** [comment]
=> npm start
=> npm test
=> need mongodb

**Comment by trollepierre** [comment]
npm install to launch

**Comment by trollepierre** [comment]
vérif mongodb https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/

**Comment by trollepierre** [comment]
config : https://github.com/OnMyTravel/api/blob/master/config/development.json 
avec mon path

**Comment by trollepierre** [comment]
brew install mongodb
sudo mkdir -p /data/db
sudo chown -R `id -u` /data/db
lancer mongod

et sur un autre terminal, lancer les tests puis start

**Comment by trollepierre** [comment]
comment on merge la branche ?

**Comment by Akhilian** [comment]
Tu push la branche, tu vas sur GIT et crée une Pull Request.
